- name: update packages
  hosts: "@@HOSTS@@"
  vars:
    insights_issues: "@@ISSUES@@"
    insights_signature_exclude: "/hosts,/vars/insights_signature,/vars/insights_issues"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldVaHBRWGh6ZG5jMU9FUXJhalZ3VGtGUlp5OUxRa0ZCYTNacE9V
      Tm9VaTlTWmtaV0syVjFZVmxsUVhCc1pVOXFTMDVwTldVeFJqTUtSRkpNTkhjMUwyRkdOR1pRVDJw
      UmRtbzBPVnB0Wmt4d1FrRlpjVWh4WTNjMFZIcHJha2RqY0dGUWNVMDBiVE5vWTIxSFJTdEJhbmhN
      TUhwcWRXVktTZ293YTJoVVNHTnFXbFprUW1WSVMzVjBOVXRRZFRoUVJIRm1jREU0UlVoUFQzcHNZ
      MjF3ZVdsblR6WkxZbU5UVjFaTmVVTjZkR0l3UzBGTFFqWktibmw2Q25GWWFUbDJkWEZ6WWt0dE5s
      cHZSa3hSTlVWQ1pqRmhZVlo2V1ZsdVFrMXNlVFp4ZFZOelpEZEVia2xLYm0weGVreE1iV1EwUzFw
      QmJWcGFkMVFyZFdVS1JrNHhRMDUwZGpaRk9GWTNTM2sxZDFVeFdYRnVRWGh4YW5FNGRrSlZiVE5R
      YURKcVVEZERhRE5MWTFkYU1IZDNTMk1yWldRME4yeE5XVTUyUkhnMU9BcFllV1JLWWxkaVdTdFha
      bGRzTTJWcU9ERTRlVzgzVUdKNU4xQlZTMGg2Tm1obGJrRllhakZZZHpKbWJFVXdja1V6SzBGSFlW
      TmFWMmRVYzNaYWFuTnJDa2hUVkdWamF6TXlhMkUzZWsxa2FEZHhSRkJ0VTNGQlkwOXRRWFZSZWxC
      VEt6UmlkbWtyUWxaRVZEaFlaSGhRVHpBMlpTdDNVV3BRY0VSWFRFaE1NMVFLUTFGeFJUVkNiVkpx
      VGxGRFVHODJNMlJVTUVwcU1USnFXa2xpY1VabVVIZHBiMWxhVTA5cVNuQmlNVmt4VWpSWFFXOXdT
      VGhzZDBjMVJrZEZaRTV2TVFvd2VFaHBkVkoyTjFjck0weFBRa3hCUldwM2QwdG9PRkE0VDI5UWVq
      SnlSMFpKY2pCSlUyeFROR0oyYkM5SmRuaDZTR2xFT1ZWMldUTjFZVk5uWVZoWkNsZzNSbkpxUW1a
      TFEzSlhRbFZTUm1oVEwyOXZhMlJRUVdWb1NsVlpZWHBsYlZRck1XNHJVM2h3YTFCMmFWQnRiRVJy
      ZDB0c2NIYzBlbTFtTms0NFZDc0tNbEVyZEdSR1pqRXlPWFJJVTJoMU1IaFhkVmhsTmpCc0wyZEdZ
      aTlpZUZaQlNrVnVabmxQY2xaa1kxUXpTMVJVVUhRdk5qSnhSWEl3T0VWamJXTkpWQXBGWnpWME5u
      YzRTbVp4TkQwS1BWaEJhME1LTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  become: true
  tasks:
    - name: check for update
      shell: "{{ ansible_facts['pkg_mgr'] }} check-update -q --advisory {{ insights_issues | regex_search('RH[SBE]A-20[\\d]{2}:[\\d]{4,5}( --advisory RH[SBE]A-20[\\d]{2}:[\\d]{4,5})*') }}"
      check_mode: no
      register: check_out
      failed_when: check_out.rc != 0 and check_out.rc != 100
      args:
        warn: false

    - when: check_out.rc == 100
      name: upgrade package
      shell: "{{ ansible_facts['pkg_mgr'] }} update -d 2 -y --advisory {{ insights_issues | regex_search('RH[SBE]A-20[\\d]{2}:[\\d]{4,5}( --advisory RH[SBE]A-20[\\d]{2}:[\\d]{4,5})*') }}"
      args:
        warn: false

    - when: check_out.rc == 100
      name: set reboot fact
      set_fact:
        insights_needs_reboot: true
